const splashName="/splash";
const mainScreenName="/main_screen";
const onboardingName = "/onboarding";
const signUpName = "/sign_up";
const logInName ="/log_in";
const errorName ="/error";
const walletName ="/wallet";
const profileName = "/profile";
const termsAndConditionsName = '/terms_and_conditions';