// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsKqVyoDVN07h4FLVEYNDSbzAcaQ8Jngk',
    appId: '1:809067603048:android:2a52f19faa1ce6d71047dd',
    messagingSenderId: '809067603048',
    projectId: 'healthline-vn',
    storageBucket: 'healthline-vn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzTe6W7oUiUDU5JU3N6Gp0wT4mh1b8_LQ',
    appId: '1:809067603048:ios:4b1ae2548b0fee921047dd',
    messagingSenderId: '809067603048',
    projectId: 'healthline-vn',
    storageBucket: 'healthline-vn.appspot.com',
    androidClientId: '809067603048-2k1hcinr2qgph0sg7kjb9rsjhlj3dlq4.apps.googleusercontent.com',
    iosClientId: '809067603048-j3i1eg5rkh6nknpubaivesksdmkh2g4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.healthline',
  );
}
